### ISSUE TITLE
Error in configuration

### ISSUE THREAD

**Issue by insanejokerhaha** [jbjorne/TEES#27]
When I try to reconfigure, there are issues with menu.py . It fails every time. If I choose to ignore, the following steps also throw exceptions like this.  And the traceback is shown below. Could you please help me with that?

*** Exception processing menu 'Models' option 'i (Install) ***
Exception: not a bzip2 file
Traceback (most recent call last):
  File "/home/zhanghao/MscProject/jbjorne-TEES-1125ab0/Utils/Menu.py", line 229, in _runHandler
    handler(*handlerArgs)
  File "/home/zhanghao/MscProject/jbjorne-TEES-1125ab0/Utils/Download.py", line 103, in downloadAndExtract
    return extractPackage(downloadFile, extractPath, packagePath)
  File "/home/zhanghao/MscProject/jbjorne-TEES-1125ab0/Utils/Download.py", line 78, in extractPackage
    package = opener(path, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1691, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1780, in bz2open
    raise ReadError("not a bzip2 file")
ReadError: not a bzip2 file

==================================== Error ====================================
There was an error processing the menu option. Please choose whether to quit or
continue
--------------------------------------------------------------------------------
    i) Ignore and continue
 *  q) Quit
================================================================================

**Comment by jbjorne** [comment]
The problem is that the model package wasn't downloaded correctly, so it cannot be unpacked (resulting in the "not a bzip2 file" error). The models are downloaded from SourceForge which seems to be having some server issues at the moment, hopefully the situation will be resolved soon.

**Comment by YuliaInn** [comment]
I am having the same problem with the classifier. I tried versions from SourceForge and the repository. Still having an error on processing the menu option. What would you recommend to do?

**Comment by jbjorne** [comment]
I tried the SVM classifier install on Ubuntu 16.04, at least installing 
the binary works correctly. What did you try to download from 
SourceForge, the classifier is not there as far as I know?

**Comment by pikapika505** [comment]
Sorry, I deleted my comment from GitHub cause I realized that I was doing it on MacOS. I will try to install it on Linux. Thank you for a rapid response!
